# site.yml

- name: Configure workstation based on operating system
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars_files:
    - packages.yml

  vars:
    is_linux: ansible_facts['system'] == 'Linux'

  pre_tasks:
    - name: Derive platform identifiers
      set_fact:
        detected_os_family: "{{ ansible_facts['os_family'] | lower | regex_replace('[^a-z0-9_]+','_') | regex_replace('_+','_') }}"
        detected_distribution: "{{ ansible_facts['distribution'] | lower | regex_replace('[^a-z0-9_]+','_') | regex_replace('_+','_') }}"
        desktop_identifiers: >-
          {{ [
              ansible_facts['env']['DESKTOP_SESSION'] | default(''),
              ansible_facts['env']['XDG_CURRENT_DESKTOP'] | default('')
            ]
            | map('lower')
            | map('regex_replace', '[^a-z0-9_]+', '_')
            | map('regex_replace', '_+', '_')
            | reject('equalto', '')
            | list
            | unique }}

    - name: Display detected platform details
      debug:
        msg: >-
          OS family={{ detected_os_family }}, distribution={{ detected_distribution }},
          desktop_identifiers={{ desktop_identifiers | default([]) }}

    - name: Ensure install_vscode_extensions flag is boolean
      set_fact:
        install_vscode_extensions: "{{ install_vscode_extensions | default(true) | bool }}"

    - name: Filter AI tools from package manifest
      when: skip_ai_tools | default(false) | bool
      set_fact:
        package_manifest: "{{ package_manifest | combine({
            'cli_tools': (package_manifest.cli_tools | rejectattr('name', 'in', ['gemini-cli', 'claude-code']) | list),
            'gui_apps': (package_manifest.gui_apps | rejectattr('name', 'equalto', 'antigravity') | list)
        }) }}"

    - name: Parse omit list
      set_fact:
        omit_list: "{{ (omit_list_str | default('')) | split(' ') | reject('equalto', '') | list }}"

    - name: Filter packages based on omit list
      when: omit_list | length > 0
      set_fact:
        package_manifest: "{{ package_manifest | combine({
            'cli_tools': (package_manifest.cli_tools | rejectattr('name', 'in', omit_list) | list),
            'gui_apps': (package_manifest.gui_apps | rejectattr('name', 'in', omit_list) | list),
            'flatpak_apps': (package_manifest.flatpak_apps | reject('in', omit_list) | list),
            'vscode_extensions': (package_manifest.vscode_extensions | reject('in', omit_list) | list),
            'fonts': (package_manifest.fonts | rejectattr('name', 'in', omit_list) | list),
            'apt_only': package_manifest.apt_only | combine({
                'common': (package_manifest.apt_only.common | reject('in', omit_list) | list)
            }),
            'dnf_only': package_manifest.dnf_only | combine({
                'common': (package_manifest.dnf_only.common | reject('in', omit_list) | list)
            })
        }) }}"

    - name: Build Homebrew package targets
      set_fact:
        brew_taps: "{{ package_manifest.brew_taps | default([]) }}"
        brew_formulae: >-
          {{ package_manifest.cli_tools | default([])
             | selectattr('brew_formula', 'defined')
             | map(attribute='brew_formula')
             | list
             | unique }}
        brew_casks: >-
          {{ (
              package_manifest.gui_apps | default([])
              | selectattr('brew_cask', 'defined')
              | map(attribute='brew_cask')
              | list
            )
            + (
              package_manifest.cli_tools | default([])
              | selectattr('brew_cask', 'defined')
              | map(attribute='brew_cask')
              | list
            )
            + (
              package_manifest.fonts | default([])
              | selectattr('brew_cask', 'defined')
              | map(attribute='brew_cask')
              | list
            )
            | unique }}

    - name: Build apt package targets
      set_fact:
        apt_packages_resolved: >-
          {{ (
                package_manifest.cli_tools | default([])
                | selectattr('apt', 'defined')
                | map(attribute='apt')
                | list
            )
            + (package_manifest.apt_only.common | default([]))
            + ((package_manifest.apt_only.by_distribution | default({})).get(detected_distribution, []))
            + (
                desktop_identifiers | default([])
                | select('in', package_manifest.apt_only.by_desktop | default({}))
                | map('extract', package_manifest.apt_only.by_desktop | default({}))
                | list
                | sum(start=[])
              )
            | unique }}

    - name: Build rpm package targets
      set_fact:
        rpm_packages_resolved: >-
          {{ (
                package_manifest.cli_tools | default([])
                | selectattr('dnf', 'defined')
                | map(attribute='dnf')
                | list
            )
            + (package_manifest.dnf_only.common | default([]))
            + ((package_manifest.dnf_only.by_distribution | default({})).get(detected_distribution, []))
            + (
                desktop_identifiers | default([])
                | select('in', package_manifest.dnf_only.by_desktop | default({}))
                | map('extract', package_manifest.dnf_only.by_desktop | default({}))
                | list
                | sum(start=[])
              )
            | unique }}

    - name: Collect VS Code extensions list
      set_fact:
        vscode_extensions_list: "{{ package_manifest.vscode_extensions | default([]) }}"

  roles:
    - role: brewPackages
      when: ansible_facts['system'] == 'Darwin'
    - role: aptPackages
      when: ansible_facts['os_family'] == 'Debian'
    - role: rpmPackages
      when: ansible_facts['os_family'] == 'RedHat'
    - role: apt_upgrade_report
      when: ansible_facts['os_family'] == 'Debian'
    - role: ohmyzsh
    - role: powerlevel10k
    - role: nvchad
      tags: ['nvchad']
    - role: vscode_extensions
      when: install_vscode_extensions | bool
    - role: davinci_resolve
      tags: ['davinci_resolve']
      when: install_davinci | default(false) | bool
    - role: synergy
      tags: ['synergy']
      when: install_synergy | default(false) | bool
    - role: nvidia_drivers
      tags: ['nvidia_drivers']
      when:
        - install_nvidia | default(false) | bool
        - ansible_facts['os_family'] == 'RedHat'
    - role: system76
      tags: ['system76']
      when:
        - install_system76 | default(false) | bool
        - ansible_facts['os_family'] == 'RedHat'
    - role: iterm2
      when: ansible_facts['system'] == 'Darwin'
