# site.yml

- name: Conigure macOS with Homebrew and VS Code packages
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars_files:
    - brewPackages.yml
  roles:
    - brewPackages
    - ohmyzsh 
    - powerlevel10k
    # - anotherRole <- Add more roles here
