---
# Role: iterm2
# Sets iTerm2 default font via Dynamic Profiles (robust method)

- name: Ensure DynamicProfiles directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles"
    state: directory
    mode: "0755"

- name: Generate GUID for iTerm2 dynamic profile
  ansible.builtin.set_fact:
    iterm2_profile_guid: "{{ lookup('password', '/dev/null length=8 chars=hexdigits') }}-{{ lookup('password', '/dev/null length=4 chars=hexdigits') }}-{{ lookup('password', '/dev/null length=4 chars=hexdigits') }}-{{ lookup('password', '/dev/null length=4 chars=hexdigits') }}-{{ lookup('password', '/dev/null length=12 chars=hexdigits') }}"

- name: Install iTerm2 dynamic profile for 0xProto font
  ansible.builtin.template:
    src: 0xproto_profile.json.j2
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/0xproto_profile.json"
    mode: "0644"

- name: Note about applying iTerm2 dynamic profile
  ansible.builtin.debug:
    msg: "Dynamic profile '0xProto 13' installed. In iTerm2, set it as default (Profiles > Profiles) or restart to auto-load."

